# Generated by Django 3.1.7 on 2021-03-15 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50, verbose_name='Группа')),
                ('group_depart', models.CharField(choices=[('FT', 'Дневное'), ('PT', 'Заочное')], default='FT', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=70, verbose_name='Название')),
                ('subject_price', models.PositiveIntegerField(verbose_name='Цена предмета')),
                ('subject_l_count', models.PositiveIntegerField(default=40, verbose_name='Кол-во лекций')),
                ('subject_p_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во практик')),
                ('subject_l_price', models.PositiveIntegerField(default=50, verbose_name='Цена за лекцию')),
                ('subject_p_price', models.PositiveIntegerField(default=100, verbose_name='Цена за практику')),
                ('whole_price', models.FloatField(default=0, editable=False, verbose_name='Общая цена за предмет')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('teacher_phone', models.CharField(max_length=13, unique=True, verbose_name='Телефон')),
                ('teacher_exp', models.PositiveIntegerField(verbose_name='Стаж')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanage.group')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanage.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanage.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=70, verbose_name='ФИО')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmanage.group')),
            ],
        ),
    ]
