# Generated by Django 3.2.3 on 2021-05-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanage', '0003_alter_teacher_teacher_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TeacherSubject',
            new_name='Classes',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(max_length=70, verbose_name='ФИО'),
        ),
    ]
