# Generated by Django 3.2.3 on 2021-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanage', '0004_auto_20210520_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_salary',
            field=models.FloatField(default=0, editable=False, verbose_name='Зарплата'),
        ),
    ]
